version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: ezface-app
    depends_on:
      - deepface
      - qdrant
    environment:
      - DATABASE_URL=file:./db.sqlite

  deepface:
    build:
      context: deepface
    image: ezface-deepface

  qdrant:
    image: qdrant/qdrant
