version: "3.9"
services:
  deepface:
    build:
      context: deepface
    image: ezface-deepface
    ports:
      - "3001:5000"

  postgres:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ezface
      POSTGRES_PASSWORD: ezface
      POSTGRES_DB: ezface

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
