version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: ezface-app
    depends_on:
      - deepface
      - qdrant
      - postgres
    environment:
      - DATABASE_URL=postgresql://ezface:ezface@postgres:5432/ezface
      - UPLOADTHING_SECRET=sk_live_1234
      - UPLOADTHING_APP_ID=1234

  deepface:
    build:
      context: deepface
    image: ezface-deepface

  qdrant:
    image: qdrant/qdrant

  postgres:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ezface
      POSTGRES_PASSWORD: ezface
      POSTGRES_DB: ezface
